import type { Metadata } from "next";
import "./globals.css";
import { GlobalProvider } from "./context/global-context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`lg:p-5 bg-[#FCFCFC] h-screen`}
      >
        <GlobalProvider>{children}</GlobalProvider>
      </body>
    </html>
  );
}
